### ISSUE TITLE
Multi-domain configuration results in filesystem error?

### ISSUE THREAD

**Issue by Hypaethral** [xinax/laravel-gettext#79] opened 2016-06-13 20:25 UTC
Following https://github.com/xinax/laravel-gettext#d-adding-source-directories-and-domains, I seem to be configuring this incorrectly, but I can't figure out what I'm doing wrong.

    ...
    'locale' => 'fr_CA',
    'supported-locales' => array(
        'en_US',
        'fr_CA',
    )
    'domain' => 'core',
    'source-paths' => array(
		'core-php' => array(
            'Http/Controllers',
            '../resources/views',
            '../resources/assets/js',
            'Console/Commands'
		),
		'core-js' => array(
			'public/build/js/bundle.js'
		)
    ),
    ...

`php artisan gettext:create` results in `/vendor/symfony/finder/Finder.php:635 - The "" directory does not exist.`
Core.po and core-php.po are created, but only for en_US.  I would expect core.po, core-php.po, and core-js.po for both en_US and fr_CA.

Changing domain to `'domain' => 'core-php'` results in the same error, and only creates core-php.po for en_US.
I do not have this problem using source-paths without the nested domain arrays.

**Comment by charles-rumley** [comment] 2016-07-12 03:46
Symfony error is caused by a non-existent path in your configuration file. A more informative error message was added in #65.

**Comment by shaggyz** [comment] 2016-10-17 16:47
Closed, since #65 is already merged.

**Closed by shaggyz** 2016-10-17 16:47 UTC
