### ISSUE TITLE
php artisan gettext:create , Error

### ISSUE THREAD

**Issue by mkwsra** [xinax/laravel-gettext#12] opened 2015-02-21 13:04 UTC
When I run this command, I'm getting the following error :
```php
$ php artisan gettext:create
/var/www/ht5/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/FileSystem.php:200 - mkdir(): No such file or directory
```

**Comment by penguen** [comment] 2015-02-21 14:38
Same error.

**Comment by shaggyz** [comment] 2015-02-23 10:16
Hey guys, sorry for the delay (weekend). I can't reproduce this error (I've tested both laravel versions 4 and 5). ¿Which laravel version and package are you using?

Remember that: package version 1.x is for laravel 4 and package version 2.x is for laravel 5.

If versions are correct, please try renaming the i18n folder and run the create command again.

Thanks for the report, i'll waiting your answers.

**Comment by csrui** [comment] 2015-02-23 15:22
We are having the same issue with branch 2.0 for Laravel 5

```
php artisan gettext:create
```

is attempting to create /app/lang/i18n instead of **/resources**/lang/i18n.

Other than this we aren't sure why but the translations aren't loaded correctly in either folder (more on this later).

**Comment by shaggyz** [comment] 2015-02-23 15:50
@csrui Ok! good report! there was an error on the default configuration file. A new version of 2.x will be released with this fix.

The fix in your existing projects is: edit the file /conf/laravel-gettext and change the 'translations-path' value from 'lang' to '../resources/lang'. It should be work.

New projects with the 2.0.1 version of this package will not have this issue.

**Closed** 2015-02-24 09:10 UTC
Labels: bug

**Comment by mkwsra** [comment] 2015-02-24 17:13
Thanks, Its working!
